projects:
  ChatAppGraphQLApi:
    schemaPath: amplify/backend/api/ChatAppGraphQLApi/build/schema.graphql
    includes:
      - src/graphql/**/*.graphql
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: angular
        generatedFileName: src/app/core/services/api.service.ts
        docsFilePath: src/graphql
        maxDepth: 2
extensions:
  amplify:
    version: 3
